<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?php echo $this->title; ?> -- KobroCMS</title>
<link href="default.css" rel="stylesheet" type="text/css" media="screen" />

<style type="text/css">

html, body {
	margin: 0;
	background-color: #FFFFFF;
}

</style>

<?php if($this->includeAdminScripts): ?>

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
	google.load("jquery", "1.3");
	google.load("jqueryui", "1.7.2");
</script>

<script type="text/javascript" src="/js/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script>

<script type="text/javascript" src="/js/admin.js"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/blitzer/jquery-ui.css" />

<?php endif; ?>
</head>
<body>

<?php echo $this->innertpl; ?>

</body>
</html>
