<div class="flower"><img src="images/img06.jpg" alt="" width="510" height="250" /></div>

<div class="post">
<div class="entry">

<a href="/?page=<?php echo $this->kobros->page->id; ?>&amp;tpl=print"><img style="float: right; margin-top: 4px;" src="/images/print.gif" /></a> 

<?php echo $this->module(array('page' => null, 'module' => $this->kobros->page->module, 'block_id' => 1)); ?>
</div>
</div>

