<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title><?php echo $this->title; ?> -- KobroCMS</title>
	<link href="default.css" rel="stylesheet" type="text/css" media="screen" />

	<style type="text/css">
		html,
		body {
			margin: 0;
			background-color: #FFFFFF;
		}
	</style>

	<?php if ($this->includeAdminScripts): ?>

		<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
		<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"
			integrity="sha256-AlTido85uXPlSyyaZNsjJXeCs07eSv3r43kyCVc8ChI=" crossorigin="anonymous"></script>


		<script type="text/javascript" src="/js/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script>

		<script type="text/javascript" src="/js/admin.js"></script>

		<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.13.3/themes/blitzer/jquery-ui.css" />

	<?php endif; ?>
</head>

<body>

	<?php echo $this->innertpl; ?>

</body>

</html>