<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?php echo $this->title; ?> -- KobroCMS</title>
<link href="default.css" rel="stylesheet" type="text/css" media="screen" />

<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
	google.load("jquery", "1.3");
</script>

<?php if($this->includeAdminScripts): ?>
<script type="text/javascript">
	google.load("jqueryui", "1.7.2");	
</script>
<script type="text/javascript" src="/js/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript" src="/js/admin.js"></script>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/blitzer/jquery-ui.css" />
<?php endif; ?>
</head>
<body>
<!-- start header -->
<div id="header">
	<div id="logo">
		<h1><a href="/"><span>Kobro</span>CMS</a></h1>
		<p>Content management for the 21st Century Enterprise</p>
	</div>
	<div id="menu">
		<ul id="main">
			<li <?php if($this->kobros->page->id == 1): ?> class="current_page_item"<?php endif; ?>><a href="/?page=1">Homepage</a></li>
			<li <?php if($this->kobros->page->id == 2): ?> class="current_page_item"<?php endif; ?>><a href="/?page=2">About Us</a></li>
			<li <?php if($this->kobros->page->id == 3): ?> class="current_page_item"<?php endif; ?>><a href="/?page=3">News</a></li>
			<li <?php if($this->kobros->page->id == 4): ?> class="current_page_item"<?php endif; ?>><a href="/?page=4&forward=/?page=111">Contact Us</a></li>
			<li <?php if($this->kobros->page->id == 5): ?> class="current_page_item"<?php endif; ?>><a href="/?page=5">Work For Us</a></li>
			<li <?php if($this->kobros->page->id == 33): ?> class="current_page_item"<?php endif; ?>><a href="/?page=33">Login</a></li>
		</ul>
	</div>

	<div id="userinfo">
	<?php echo $this->module(array('module' => 'User', 'action' => 'info', 'target' => 33)); ?>
	</div>
	
</div>
<!-- end header -->
<div id="wrapper">
	<!-- start page -->
	<div id="page">
		<div id="sidebar1" class="sidebar">
			<ul>
				<?php echo $this->module(array('module' => 'News', 'page' => 3, 'action' => 'headlines', 'number' => 3)); ?>
			    <?php echo $this->module(array('module' => 'Poll', 'action' => 'default', 'question_id' => 1, 'forward'  => '/?page=1')); ?>
            </ul>
            
            
            
		</div>
		<!-- start content -->
		<div id="content">
			
			<?php echo $this->innertpl; ?>

		</div>
		<!-- end content -->
		<!-- start sidebars -->
		<div id="sidebar2" class="sidebar">
			<ul>
				<li>
					<?php echo $this->module(array('module' => 'Search', 'action' => 'quicksearch', 'page' => 88)); ?>
				</li>
				<li>
					<h2>Hot Topics</h2>
					<ul>
						<li><a href="#">Taking KobroScript to the max</a></li>
						<li><a href="#">Objects WTF?</a></li>
						<li><a href="#">The Mighty KobrORM: Why KobrosQL is so much better?</a></li>
						<li><a href="#">Module &quot;Module Installer&quot; required to install modules. How to install it?</a></li>
					</ul>
				</li>
			</ul>
		</div>
		<!-- end sidebars -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end page -->
</div>
<div id="footer">
	<p class="copyright">&copy;&nbsp;&nbsp;2009-2011 <a href="http://dr-kobros.com/foundation" target="_blank">The Dr. Kobros Foundation</a> &nbsp;&bull;&nbsp; Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	<p class="link">
		<a href="/?page=99">Privacy Policy</a>&nbsp;&#8226;&nbsp;
		<a href="/?page=100">Terms of Use</a>
	</p>
</div>

<script type="text/javascript" src="/js/kobrotracker.js"></script>
<script type="text/javascript">
var kt = KobroTracker.get('kobrocms');
// Initial tracking for page, kobrotracker then also listen anchor change. KobroTracker very wise my friend!
kt.track();
</script>

</body>
</html>
