<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?php echo $this->title; ?> -- KobroCMS</title>
</head>
<body>
<?php echo $this->innertpl; ?>

<script type="text/javascript" src="/js/kobrotracker.js"></script>
<script type="text/javascript">
var kt = KobroTracker.get('kobrocms');
// Initial tracking for page, kobrotracker then also listen anchor change. KobroTracker very wise my friend!
kt.track();
</script>

</body>
</html>
