<?php foreach($this->news as $item): ?>
<div class="post">
    <h2 class="title"><a href="/?page=<?php echo htmlspecialchars($this->page_id, ENT_NOQUOTES, 'UTF-8'); ?>&amp;action=view&amp;id=<?php echo htmlspecialchars($item->id, ENT_NOQUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($item->title, ENT_NOQUOTES, 'UTF-8'); ?></a></h2>
				<p class="byline"><small>Posted on <?php echo htmlspecialchars($item->created, ENT_NOQUOTES, 'UTF-8'); ?> by admin</small></p>
				<div class="entry">
					<?php echo $item->content; ?>
					<p class="links"><a href="/?page=<?php echo htmlspecialchars($this->page_id, ENT_NOQUOTES, 'UTF-8'); ?>&amp;action=view&amp;id=<?php echo htmlspecialchars($item->id, ENT_NOQUOTES, 'UTF-8'); ?>" class="more">&laquo;&laquo;&nbsp;&nbsp;Read More&nbsp;&nbsp;&raquo;&raquo;</a></p>
				</div>
			</div>
<?php endforeach; ?>
