<div class="post">
<div class="entry">


<h2>Login</h2>

<?php if($this->user->role == 'anonymous'): ?>

<form method="post" action="/?page=<?php echo $this->kobros->page->id; ?>&amp;action=login">

<?php if($this->error): ?>
<p class="error">
<?php echo $this->error; ?>
</p>
<?php endif; ?>

<label>Login</label>
<input type="text" name="login" />

<label>Password</label>
<input type="password" name="password" />

<button type="submit">Login</button>

</form>

<?php else: ?>

<p>
You are already logged in, oh big one.
</p>

<a href="/?page=<?php echo $this->kobros->page->id; ?>&amp;action=logout">Logout</a>

<?php endif; ?>

</div>
</div>
